baseurl = "http://mahoffman.github.io/"
languageCode = "en-us"
title = "Mark Anthony Hoffman"
disqusShortname = "mh3279"
paginate = 10

[params]

	title = "Mark Anthony Hoffman"
	subtitle = "PhD Candidate | Sociology | Columbia"
	copyright = "Released under the MIT license."

	# You can choose between green, orange, red and blue.
	themeColor = "blue"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = ""

	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "Mark Anthony Hoffman"
	bio = "Mark is a second year PhD Candidate at Columbia University and a fellow at the Interdisciplinary Center for Innovative Theory and Empirics (INCITE)."
	description = "Your description of the blog"
	location = "New York, New York" # optional
	github = "http://github.com/mahoffman" # optional

	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs.
	comments = "disqus"

	# Customize or translate the strings
	keepReadingStr = "Keep reading"
	backtotopStr = "Back to top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - Page not found"
